/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import oovv.DTOEntrada;
import oovv.Maex;

/**
 *
 * @author Administrador
 */
public class DEntrada extends javax.swing.JDialog {

    /**
     * Creates new form DEntrada
     */
    public DEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public void setOidor(ActionListener oidor) {
        bCancela.addActionListener(oidor);
        bValida.addActionListener(oidor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eTipusCamp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfParaula = new javax.swing.JTextField();
        eAccio = new javax.swing.JLabel();
        tfPosicio = new javax.swing.JTextField();
        bValida = new javax.swing.JButton();
        bCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        eTipusCamp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eTipusCamp.setText("paraula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("posició");

        tfParaula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        eAccio.setBackground(new java.awt.Color(51, 51, 255));
        eAccio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eAccio.setForeground(new java.awt.Color(255, 255, 255));
        eAccio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eAccio.setText("acció");
        eAccio.setOpaque(true);

        tfPosicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bValida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bValida.setText("Valida");

        bCancela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bCancela.setText("Cancel·la");
        bCancela.setActionCommand("Cancela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eAccio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(eTipusCamp))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfParaula)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bValida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(bCancela))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPosicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eAccio)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfParaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTipusCamp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPosicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bValida)
                    .addComponent(bCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DEntrada dialog = new DEntrada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancela;
    private javax.swing.JButton bValida;
    private javax.swing.JLabel eAccio;
    private javax.swing.JLabel eTipusCamp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfParaula;
    private javax.swing.JTextField tfPosicio;
    // End of variables declaration//GEN-END:variables

    public DTOEntrada getDto() throws Maex {
        if (accio == 0 || accio == 3 || accio == 4|| accio == 5) {
            return new DTOEntrada(tfParaula.getText());
        }
        if (accio == 2) {
            return new DTOEntrada(Integer.parseInt(tfPosicio.getText()));
        }
        if (accio == 6) {
            return new DTOEntrada(tfParaula.getText(), tfPosicio.getText());
        }
        return new DTOEntrada(tfParaula.getText(), Integer.parseInt(tfPosicio.getText()));
    }

    private int accio;

    public void configura(int accio) {
        this.accio = accio;
        String[] accions = {"Afegeix una paraula",
            "Insereix una paraula en",
            "Visualitza una paraula",
            "Afegeix les paraules d'un text",
            "Defineix els separadors",
            "Esborra les paraules d’un text",
            "Esborra paraula/es"};
        String[] eTipusCampT = {"paraula",
            "paraula",
            "paraula",
            "text",
            "separadors",
            "text",
            "paraula"};
        Boolean[] tfParaulaA = {true, true, false, true, true, true, true};
        Boolean[] tfPosicioA = {false, true, true, false, false, false, true};

        eAccio.setText(accions[accio]);
        eTipusCamp.setText(eTipusCampT[accio]);
        tfParaula.setEnabled(tfParaulaA[accio]);
        tfPosicio.setEnabled(tfPosicioA[accio]);

        setVisible(true);
    }

    public String getParaula() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
