/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author Administrador
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void setOidor(ActionListener oidor) {
        JMenuItem[] mItem = {miAMajuscules, miAfegirParaulesText, miAfegirUnaParaula, miAfegirUnaParaulaEn,
            miDefineixSeparadors, miEixir, miEsborrarParaules, miEsborrarParaulesRepetides, miEsborrarUnaParaula,
            miInicialAMjuscules, miVisualitzaLesParaules, miVisualitzaUnaParaula,
            miGuardaLlista, miAfegeixLlista, miRecuperaLlista,
            miOrdenaNombreVocals, miOrdenaLongitudParaula, miOrdenaAlfabeticament};
        for (JMenuItem menuItem : mItem) {
            menuItem.addActionListener(oidor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taPantalla = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDefineixSeparadors = new javax.swing.JMenuItem();
        miAMajuscules = new javax.swing.JMenuItem();
        miInicialAMjuscules = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        llista = new javax.swing.JMenu();
        miGuardaLlista = new javax.swing.JMenuItem();
        miAfegeixLlista = new javax.swing.JMenuItem();
        miRecuperaLlista = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miEixir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAfegirUnaParaula = new javax.swing.JMenuItem();
        miAfegirUnaParaulaEn = new javax.swing.JMenuItem();
        miAfegirParaulesText = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miEsborrarUnaParaula = new javax.swing.JMenuItem();
        miEsborrarParaulesRepetides = new javax.swing.JMenuItem();
        miEsborrarParaules = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miVisualitzaUnaParaula = new javax.swing.JMenuItem();
        miVisualitzaLesParaules = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miOrdenaAlfabeticament = new javax.swing.JMenuItem();
        miOrdenaLongitudParaula = new javax.swing.JMenuItem();
        miOrdenaNombreVocals = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taPantalla.setColumns(20);
        taPantalla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taPantalla.setRows(5);
        jScrollPane1.setViewportView(taPantalla);

        jMenu1.setText("Accions");

        miDefineixSeparadors.setText("definir separadors");
        miDefineixSeparadors.setToolTipText("Defineix els separadors de les paraules d'un text");
        jMenu1.add(miDefineixSeparadors);

        miAMajuscules.setText("passar a majúscules");
        miAMajuscules.setToolTipText("Passa a majúscules totes les paraules");
        jMenu1.add(miAMajuscules);

        miInicialAMjuscules.setText("posar inicial a majúscules");
        miInicialAMjuscules.setToolTipText("Posa la primera lletra a majúscules de totes les paraules de la llista");
        jMenu1.add(miInicialAMjuscules);
        jMenu1.add(jSeparator1);

        llista.setText("Llista");

        miGuardaLlista.setText("Guarda");
        miGuardaLlista.setToolTipText("Guarda la llista en el fitxer");
        miGuardaLlista.setActionCommand("Guarda llista fitxer");
        llista.add(miGuardaLlista);

        miAfegeixLlista.setText("Afegeix");
        miAfegeixLlista.setToolTipText("Afegeix la llista al fitxer");
        miAfegeixLlista.setActionCommand("Afegeix llista fitxer");
        llista.add(miAfegeixLlista);

        miRecuperaLlista.setText("Recupera");
        miRecuperaLlista.setToolTipText("Recupera la llista del fitxer");
        miRecuperaLlista.setActionCommand("Recupera llista fitxer");
        llista.add(miRecuperaLlista);

        jMenu1.add(llista);
        jMenu1.add(jSeparator2);

        miEixir.setText("Eixir");
        miEixir.setToolTipText("Tanca l’aplicació");
        jMenu1.add(miEixir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Afegir");

        miAfegirUnaParaula.setText("UNA paraula");
        miAfegirUnaParaula.setToolTipText("Insereix una paraula al final");
        miAfegirUnaParaula.setActionCommand("afegir una paraula");
        jMenu2.add(miAfegirUnaParaula);

        miAfegirUnaParaulaEn.setText("UNA paraula en");
        miAfegirUnaParaulaEn.setToolTipText("Insereix una paraula en la posició indicada");
        miAfegirUnaParaulaEn.setActionCommand("afegir una  paraula en");
        jMenu2.add(miAfegirUnaParaulaEn);

        miAfegirParaulesText.setText("paraules d'un text");
        miAfegirParaulesText.setToolTipText("Afegeix les paraules d'un text llegit de teclat ");
        miAfegirParaulesText.setActionCommand("afegir paraules d'un text");
        jMenu2.add(miAfegirParaulesText);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Esborrar");

        miEsborrarUnaParaula.setText("UNA paraula");
        miEsborrarUnaParaula.setToolTipText("Esborra la paraula que li indiquem");
        miEsborrarUnaParaula.setActionCommand("esborrar una paraula");
        jMenu3.add(miEsborrarUnaParaula);

        miEsborrarParaulesRepetides.setText("paraules repetides");
        miEsborrarParaulesRepetides.setToolTipText("Elimina les paraules repetides, totes menys una");
        miEsborrarParaulesRepetides.setActionCommand("esborrar paraules repetides");
        jMenu3.add(miEsborrarParaulesRepetides);

        miEsborrarParaules.setText("paraules d'un text");
        miEsborrarParaules.setToolTipText("Esborra les paraules del text llegit de teclat");
        miEsborrarParaules.setActionCommand("esborrar paraules d'un text");
        jMenu3.add(miEsborrarParaules);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Visualitzar");

        miVisualitzaUnaParaula.setText("UNA paraula");
        miVisualitzaUnaParaula.setToolTipText("Visualitza la paraula en la posició indicada");
        miVisualitzaUnaParaula.setActionCommand("visualitzar una  paraula");
        jMenu4.add(miVisualitzaUnaParaula);

        miVisualitzaLesParaules.setText("totes les paraules");
        miVisualitzaLesParaules.setToolTipText("Visualitza la llista completa, la posició i la paraula");
        miVisualitzaLesParaules.setActionCommand("visualitzar totes les paraules");
        jMenu4.add(miVisualitzaLesParaules);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ordena");

        miOrdenaAlfabeticament.setText("alfabèticament");
        miOrdenaAlfabeticament.setToolTipText("Ordena alfabèticament les paraules");
        miOrdenaAlfabeticament.setActionCommand("ordena alfabèticament");
        jMenu5.add(miOrdenaAlfabeticament);

        miOrdenaLongitudParaula.setText("longitud paraula");
        miOrdenaLongitudParaula.setToolTipText("ordena per la longitud de les paraules");
        miOrdenaLongitudParaula.setActionCommand("ordena per la longitud");
        jMenu5.add(miOrdenaLongitudParaula);

        miOrdenaNombreVocals.setText("nombre de vocals");
        miOrdenaNombreVocals.setToolTipText("ordena pel nombre de vocals de les paraules");
        miOrdenaNombreVocals.setActionCommand("ordena pel nombre de vocals");
        jMenu5.add(miOrdenaNombreVocals);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu llista;
    private javax.swing.JMenuItem miAMajuscules;
    private javax.swing.JMenuItem miAfegeixLlista;
    private javax.swing.JMenuItem miAfegirParaulesText;
    private javax.swing.JMenuItem miAfegirUnaParaula;
    private javax.swing.JMenuItem miAfegirUnaParaulaEn;
    private javax.swing.JMenuItem miDefineixSeparadors;
    private javax.swing.JMenuItem miEixir;
    private javax.swing.JMenuItem miEsborrarParaules;
    private javax.swing.JMenuItem miEsborrarParaulesRepetides;
    private javax.swing.JMenuItem miEsborrarUnaParaula;
    private javax.swing.JMenuItem miGuardaLlista;
    private javax.swing.JMenuItem miInicialAMjuscules;
    private javax.swing.JMenuItem miOrdenaAlfabeticament;
    private javax.swing.JMenuItem miOrdenaLongitudParaula;
    private javax.swing.JMenuItem miOrdenaNombreVocals;
    private javax.swing.JMenuItem miRecuperaLlista;
    private javax.swing.JMenuItem miVisualitzaLesParaules;
    private javax.swing.JMenuItem miVisualitzaUnaParaula;
    private javax.swing.JTextArea taPantalla;
    // End of variables declaration//GEN-END:variables

    public void mostra(String txt) {
        taPantalla.append(txt+"\n");
    }


}
