/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import oovv.Cercle;
import oovv.Figura;
import oovv.Punt;
import oovv.Quadrat;
import oovv.Rectangle;

/**
 *
 * @author Profesor
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MiVentana
     */
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taPantalla = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        bCreaCercle = new javax.swing.JButton();
        bCreaRectangle = new javax.swing.JButton();
        bCreaQuadrat = new javax.swing.JButton();
        bCreaAleatori = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfX = new javax.swing.JTextField();
        eValor = new javax.swing.JLabel();
        tfY = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        eValor3 = new javax.swing.JLabel();
        tfRadi = new javax.swing.JTextField();
        eValor2 = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        eValor1 = new javax.swing.JLabel();
        tfAmplada = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        miGuarda = new javax.swing.JMenuItem();
        miLlig = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miTancar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miVeureTot = new javax.swing.JMenuItem();
        miVeureDistanciaXY = new javax.swing.JMenuItem();
        miVeureDistanciaFig = new javax.swing.JMenuItem();
        miVeureMaxMin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miEliminaFigXY = new javax.swing.JMenuItem();
        miEliminaFigures = new javax.swing.JMenuItem();
        miEliminaTot = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miOrdenaArea = new javax.swing.JMenuItem();
        miOrdenaPerimetre = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miSumaArees = new javax.swing.JMenuItem();
        miSumaPerimetres = new javax.swing.JMenuItem();
        miSumaZona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taPantalla.setColumns(20);
        taPantalla.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        taPantalla.setRows(5);
        jScrollPane1.setViewportView(taPantalla);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Afegeix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Condensed", 0, 24))); // NOI18N

        bCreaCercle.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bCreaCercle.setText("CERCLE");
        bCreaCercle.setActionCommand("afegeix cercle");
        bCreaCercle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        bCreaRectangle.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bCreaRectangle.setText("RECTANGLE");
        bCreaRectangle.setActionCommand("afegeix rectangle");
        bCreaRectangle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        bCreaQuadrat.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bCreaQuadrat.setText("QUADRAT");
        bCreaQuadrat.setActionCommand("afegeix quadrat");
        bCreaQuadrat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        bCreaAleatori.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bCreaAleatori.setText("ALEATORI");
        bCreaAleatori.setActionCommand("afegeix aleatori");
        bCreaAleatori.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Posició X=");

        tfX.setColumns(5);
        tfX.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfX.setText("4");

        eValor.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eValor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eValor.setText("Y=");

        tfY.setColumns(5);
        tfY.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfY.setText("10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCreaCercle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCreaRectangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCreaQuadrat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(eValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCreaAleatori, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfX, tfY});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bCreaAleatori, bCreaCercle, bCreaQuadrat, bCreaRectangle});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eValor)
                        .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCreaCercle)
                        .addComponent(bCreaRectangle)
                        .addComponent(bCreaQuadrat)
                        .addComponent(bCreaAleatori)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        eValor3.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eValor3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eValor3.setText("Radi=");

        tfRadi.setColumns(5);
        tfRadi.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfRadi.setText("10");

        eValor2.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eValor2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eValor2.setText("Altura/Costat=");

        tfAltura.setColumns(5);
        tfAltura.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfAltura.setText("4");

        eValor1.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eValor1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eValor1.setText("Amplada=");

        tfAmplada.setColumns(5);
        tfAmplada.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfAmplada.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eValor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(eValor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eValor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eValor2)
                    .addComponent(tfAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eValor1)
                    .addComponent(tfRadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eValor3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Fitxer");

        miGuarda.setText("Guarda");
        jMenu2.add(miGuarda);

        miLlig.setText("Llig");
        jMenu2.add(miLlig);
        jMenu2.add(jSeparator1);

        miTancar.setText("Tancar");
        jMenu2.add(miTancar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Visualitza");

        miVeureTot.setText("Tot");
        miVeureTot.setActionCommand("veure tot");
        jMenu3.add(miVeureTot);

        miVeureDistanciaXY.setText("distància a XY");
        miVeureDistanciaXY.setActionCommand("veure distància a XY");
        jMenu3.add(miVeureDistanciaXY);

        miVeureDistanciaFig.setText("distància figures");
        miVeureDistanciaFig.setActionCommand("veure distància figures");
        jMenu3.add(miVeureDistanciaFig);

        miVeureMaxMin.setText("Màxim i Mínim");
        miVeureMaxMin.setActionCommand("veure màxim i Mínim");
        jMenu3.add(miVeureMaxMin);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Elimina");

        miEliminaFigXY.setText("Figura en X,Y");
        miEliminaFigXY.setActionCommand("elimina figura en X,Y");
        jMenu4.add(miEliminaFigXY);

        miEliminaFigures.setText("Figures");
        miEliminaFigures.setActionCommand("elimina figures");
        jMenu4.add(miEliminaFigures);

        miEliminaTot.setText("Tot");
        miEliminaTot.setActionCommand("elimina tot");
        jMenu4.add(miEliminaTot);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ordena");

        miOrdenaArea.setText("Àrea");
        miOrdenaArea.setActionCommand("ordena àrea");
        jMenu5.add(miOrdenaArea);

        miOrdenaPerimetre.setText("Perímetre");
        miOrdenaPerimetre.setActionCommand("ordena perímetre");
        jMenu5.add(miOrdenaPerimetre);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Suma");

        miSumaArees.setText("Àrees");
        miSumaArees.setActionCommand("suma arees");
        jMenu6.add(miSumaArees);

        miSumaPerimetres.setText("Perímetres");
        miSumaPerimetres.setActionCommand("suma perimetres");
        jMenu6.add(miSumaPerimetres);

        miSumaZona.setText("Zona");
        miSumaZona.setActionCommand("suma zona");
        jMenu6.add(miSumaZona);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreaAleatori;
    private javax.swing.JButton bCreaCercle;
    private javax.swing.JButton bCreaQuadrat;
    private javax.swing.JButton bCreaRectangle;
    private javax.swing.JLabel eValor;
    private javax.swing.JLabel eValor1;
    private javax.swing.JLabel eValor2;
    private javax.swing.JLabel eValor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miEliminaFigXY;
    private javax.swing.JMenuItem miEliminaFigures;
    private javax.swing.JMenuItem miEliminaTot;
    private javax.swing.JMenuItem miGuarda;
    private javax.swing.JMenuItem miLlig;
    private javax.swing.JMenuItem miOrdenaArea;
    private javax.swing.JMenuItem miOrdenaPerimetre;
    private javax.swing.JMenuItem miSumaArees;
    private javax.swing.JMenuItem miSumaPerimetres;
    private javax.swing.JMenuItem miSumaZona;
    private javax.swing.JMenuItem miTancar;
    private javax.swing.JMenuItem miVeureDistanciaFig;
    private javax.swing.JMenuItem miVeureDistanciaXY;
    private javax.swing.JMenuItem miVeureMaxMin;
    private javax.swing.JMenuItem miVeureTot;
    private javax.swing.JTextArea taPantalla;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfAmplada;
    private javax.swing.JTextField tfRadi;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    // End of variables declaration//GEN-END:variables

    public void setOidor(ActionListener oidor) {
        AbstractButton[] elsBotons = {
            bCreaAleatori, bCreaCercle, bCreaQuadrat, bCreaRectangle,
            miEliminaFigXY, miEliminaFigures, miEliminaTot, 
            miGuarda, miLlig,
            miOrdenaArea, miOrdenaPerimetre, 
            miSumaArees,  miSumaPerimetres, miSumaZona,
            miTancar,
            miVeureDistanciaFig, miVeureDistanciaXY, miVeureMaxMin, miVeureTot};
        for (AbstractButton boto : elsBotons) {
            boto.addActionListener(oidor);
        }
    }

    public void mostra(String text) {
        taPantalla.append(text);
    }

    public Punt getPuntXY() {
        return new Punt(Integer.parseInt(tfX.getText()),
                Integer.parseInt(tfY.getText()));
    }

    public Cercle getCercle() {
        Cercle c = null;
        try {
            c = new Cercle(Double.parseDouble(tfRadi.getText()));
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El valor ha de ser un double");
        }
        try {
            c.setPosicio(new Punt(Integer.parseInt(tfX.getText()),
                    Integer.parseInt(tfY.getText())));
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El valor ha de ser un enter");
        }
        return c;
    }

    public Figura getQuadrat() {
        return new Quadrat(Double.parseDouble(tfAltura.getText()),
                Integer.parseInt(tfX.getText()),
                Integer.parseInt(tfY.getText()));
    }

    public Figura getRectangle() {
        return new Rectangle(Double.parseDouble(tfAltura.getText()),
                Double.parseDouble(tfAmplada.getText()),
                Integer.parseInt(tfX.getText()),
                Integer.parseInt(tfY.getText()));
    }

}
